### ISSUE TITLE
issue with column --json command

### ISSUE THREAD

**Issue by yyovkov** [dusharu/ZBX_Disk_Stat#1]
Hi Andrey, 

nice plugin!

I was testing it with CentOS 7 and ubuntu 18.04. There the command `column` doesn't have option `--json`.
This option is presented in CentOS 8.

Rather this is not issue, as you have provided version which is using `aws` in your first commit. Possibly is worthy to mention this requirements in the README file, and in the zabbix plugins page.

**Comment by dusharu** [comment]
Hi Yovko,
Thank you for Information.

I'm start working on this problem.

**Comment by dusharu** [comment]
For Infromation: 
Column start support json on [version 2.30](https://mirrors.edge.kernel.org/pub/linux/utils/util-linux/v2.30/v2.30-ReleaseNotes)

Last versions - [2.35](https://mirrors.edge.kernel.org/pub/linux/utils/util-linux/)

On Debian 10(buster(stable)) - [2.33](https://packages.debian.org/search?keywords=util-linux)
On Debian 9(stretch (oldstable)) - [2.29](https://packages.debian.org/search?keywords=util-linux)

On Ubuntu 18.04(bionic) - [2.31](https://packages.ubuntu.com/ru/bionic/util-linux)
On Ubuntu 16.04(xenial) - [2.27](https://packages.ubuntu.com/ru/bionic/util-linux)

On Centos-7 [2.23](https://pkgs.org/download/util-linux)
On Centos-8 [2.32](https://pkgs.org/download/util-linux)

On Gentoo - [2.34](https://packages.gentoo.org/packages/sys-apps/util-linux)

**Comment by dusharu** [comment]
@yyovkov
Are you agree with this decision?

[README.md](https://github.com/dusharu/ZBX_Disk_Stat#install) :
```
# For RHEL/CentOS-8, Debian-10(buster), Ubuntu-18.04(Xenial), Gentoo
curl -O 'https://raw.githubusercontent.com/dusharu/ZBX_Disk_Stat/master/config_zabbix-agent/Disk_Stat.conf'
# For old system
curl -o Disk_Stat.conf 'https://raw.githubusercontent.com/dusharu/ZBX_Disk_Stat/master/config_zabbix-agent/Disk_Stat_awk.conf'
```

**Comment by dusharu** [comment]
Add Install section to https://share.zabbix.com/operating-systems/linux/disk-stat
