### ISSUE TITLE
can't get values

### ISSUE THREAD

**Issue by emper0r** [dusharu/ZBX_Disk_Stat#2]
Hi..
i'm using centos 7.4 
my cut version is 8.22 so don't have -z option for now, that option comming on 8.32, in any case I delete that -z on the code and from console I can get result in this way

```
zabbix_get -s dbtest1 -k custom.blkdev.discovery
{
        "data":[
                {       "{#DEVBLK}":"fd0"       },
                {       "{#DEVBLK}":"sr0"       },
                {       "{#DEVBLK}":"sdb"       },
                {       "{#DEVBLK}":"sda"       },
                {       "{#DEVBLK}":"sda1"      },
                {       "{#DEVBLK}":"sda2"      },
                {       "{#DEVBLK}":"cl-root
"       },
                {       "{#DEVBLK}":"cl-swap
"       },
                {       "{#DEVBLK}":"mysqlvg-mysqllv
"       }
        ]
}
```

seems fine.. but after import and did all steps.. regex, import, etc.. I can't get discovery files.. the output error is. 

thanks for your work I appreciate the help 

![image](https://user-images.githubusercontent.com/819042/87816880-4e0f4900-c868-11ea-960a-dfaa5cedc868.png)

**Comment by dusharu** [comment]
Hi,
I find error and try to fix it tomorow, when I get my notebook.

Thank you for your feedback.

**Comment by dusharu** [comment]
**Fix it** 
commit 764f210

**Comment by emper0r** [comment]
Hi again @dusharu 

Thanks so much... now works fine..!
