### ISSUE TITLE
Cannot link template with linux host

### ISSUE THREAD

**Issue by iichernenko** [dusharu/ZBX_Disk_Stat#6]
Hi! I do not bind the template to the Linux host, I get an error:

> Details Cannot update host
> - Missing key "custom.blkdev.read_operation_ps[{#DEVBLK}]" for host "host01".
> - Graph "IOPS on {#DEVBLK}" cannot inherit. No required items on "host01".

I am using zabbix version 5.0.19 .

**Comment by dusharu** [comment]
Hi,
1. Do you add config to the `agent config`?
https://github.com/dusharu/ZBX_Disk_Stat#install

2. Can you describe steps to reproduce the problem?  
I start this template on Zabbix-3, and now it's working on Zabbix-5.2.6 in my Home.

**Comment by dusharu** [comment]
Close issue.  
Cause: not answer
