### ISSUE TITLE
No compatible with 5.0

### ISSUE THREAD

**Issue by duven87** [dusharu/ZBX_Disk_Stat#7]
![image](https://github.com/dusharu/ZBX_Disk_Stat/assets/24485101/24704574-0b78-479f-afc0-b00d2ec3176b)

It doesnt work with Zabbix 5.0
I changed the description to 5.0 but anyway when I try to import it:

`Invalid tag "/zabbix_export/groups/group(1)": unexpected tag "uuid".
`
I removed all lines with uuid and after that another error:

`Invalid tag "/zabbix_export/templates/template(1)/discovery_rules/discovery_rule(1)/item_prototypes/item_prototype(1)": unexpected tag "tags".
`

**Comment by dusharu** [comment]
You can try previous version  
https://github.com/dusharu/ZBX_Disk_Stat/blob/d63f5f379a5d7210b2d09ca8d9dc8462d4cba81d/Template_ZBX/ZBX_Disk_Stat.xml

It need UserParameters  
https://github.com/dusharu/ZBX_Disk_Stat/blob/d63f5f379a5d7210b2d09ca8d9dc8462d4cba81d/config_zabbix-agent/Disk_Stat_awk.conf

**Comment by dusharu** [comment]
Good News.  
I install Zabbix-5.0 and make Template for Zabbix-5.0:  
https://github.com/dusharu/ZBX_Disk_Stat/tree/master/Template_ZBX/5_0

**Comment by duven87** [comment]
![image](https://github.com/dusharu/ZBX_Disk_Stat/assets/24485101/90f4230c-a75a-46ab-8bdf-037dd5e4fd78)

Cool!! Thank you very much! :)
I still have to test the script and test it on a host.
I will let you know

**Comment by duven87** [comment]
It works! 
Thanks you very much again :)
![image](https://github.com/dusharu/ZBX_Disk_Stat/assets/24485101/60d036a2-e75e-4004-8ed3-cfd4179de4c1)
